### ISSUE TITLE
Mouse select event hides is considered like a click event

### ISSUE THREAD

**Issue by DhouhaBchir** [castlabs/electron-releases#53] opened 2020-02-24 17:22 UTC
Hello,
I face a problem since passing to electron castlabs 7.1.7.
In fact, the mouse event when selecting the text on the input, is considered like a click event, when the cursor passes over the dimmer (the black zone around the modal). (see attached video with electron 7.1.7).
That works fine with electron 4.1.5 (see attached video with electron 4.1.5)
Anyone have any ideas about this please ?
Thanks.
Dhouha.

[with Electron 7.1.7.zip](https://github.com/castlabs/electron-releases/files/4245823/with.Electron.7.1.7.zip)
[with Electron 4.1.5.zip](https://github.com/castlabs/electron-releases/files/4245821/with.Electron.4.1.5.zip)

**Comment by khwaaj** [comment] 2020-02-24 18:27
Hi,

First off, is this reproducible using the latest version in the series,  [v7.1.13-wvvmp](https://github.com/castlabs/electron-releases/releases/tag/v7.1.13-wvvmp)? And does it work better if you test using [stock electron](https://github.com/electron/electron/releases), [v7.1.7](https://github.com/electron/electron/releases/tag/v7.1.7) or [v7.1.13](https://github.com/electron/electron/releases/tag/v7.1.13).

I ask because this does not sound like an issue related to the changes we have made to electron to support Widevine, so I'm thinking it might exist in stock electron as well, and it might even be fixed in a later release.

Thanks,
Emil

**Comment by DhouhaBchir** [comment] 2020-02-25 09:07
Hello,

Thank you for your fast answer, actually, the issue is reproductible with  v7.1.13-wvvmp and with stock electron,  v7.1.7 and v7.1.13.
I will create an issue on electron repository.

Thanks,
Dhouha.

**Comment by khwaaj** [comment] 2020-03-04 00:04
Since this is now tracked by https://github.com/electron/electron/issues/22372, I'm closing this issue here.

**Closed by khwaaj** 2020-03-04 00:04 UTC
