### ISSUE TITLE
getting widevine-license error on the spotify web player

### ISSUE THREAD

**Issue by chris-hinds** [castlabs/electron-releases#56] opened 2020-04-24 09:30 UTC
I started building a Spotify electron app a while back using the casklabs electron build, it worked fine back then (nearly a year ago). However spinning up the app now U see an issues where Spotify playback starts, then skips tracks then stops. 

Looking in the console I am seeing requests being made to `https://api.spotify.com/v1/widevine-license/v1/audio/license?exp=1587806765&cp=&tok=xxxxx`

These fail with a 500 error message saying `widevine error`. I am not making these requests so am wondering if electron is making these by default?

**Comment by khwaaj** [comment] 2020-04-24 11:36
These are requests for licenses made by the Widevine CDM on behalf of whatever media player you are using (if you are not interacting with it through EME yourself). I can't say for sure why you are seeing 500 errors from the server without further details/investigation but, unless you have a production VMP signing certificate to sign your electron app, that might be it. Widevine enforces VMP more strictly now than it did before and this may be the type of case that is affected by the change.

**Comment by turbidwater** [comment] 2020-05-27 17:36
I am experiencing something similar to this as well. We had a simple DASH player in Electron that played fine on both Mac and PC back in October 2019. Looking at it recently, PC works, but the Mac version is now getting errors (403s and 500s). The versions of the environment are:
Chrome: 80.0.3987.165
Electron: 8.3.0
Node: 12.13.0
Widevine CDM: 4.10.1582.2

The DRM content plays fine in Chrome on Mac, but the exact same player in Electron throws access denied errors when run in Electron on Mac. However, this issue does not persist across all Widevine assets. Of the 9 publicly available assets I tried, 4 work in the browser, but not in Electron. 5 work in both the browser and Electron.

Are there any updates that would have occurred to the CDM or how these Electron builds interact with it that would have affected Mac but not PC?

**Comment by khwaaj** [comment] 2020-05-27 18:41
I'm not aware of anything that has changed that would cause these errors. Based on the HTTP codes you get back my first guess would be some kind of VMP related error, either that your production signature failed somehow (e.g. expiry, revocation or maybe a mistake) or that something changed in the binary it protects after you generated the signature. There are also some restrictions when using symlinks and/or other forms of filesystem aliases to reference the location of electron or the CDM that could cause similar issues.

If these are public assets, maybe I could try to play them back here and see if I can reproduce/diagnose the issue. Do you have public links for them I can access?

**Comment by turbidwater** [comment] 2020-05-27 19:26
Hi @khwaaj I have a zip of the basic DASH player I put together for testing to make sure it wasn't our player. https://drive.google.com/file/d/1QrZcaC5_Xs4jsFdYZLONLi2Q0QW_gZvd/view?usp=sharing 

It has a combo box with all the assets in it, but here are the necessary bits of info for playback:
`
var media = {
            appspot: {
                media: 'https://bitmovin-a.akamaihd.net/content/art-of-motion_drm/mpds/11331.mpd',
                license: 'https://widevine-proxy.appspot.com/proxy'
            },
            shakaSintel: {
                media: 'https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd',
                license: 'https://cwip-shaka-proxy.appspot.com/no_auth'
            },
            shakaAngel: {
                media: 'https://storage.googleapis.com/shaka-demo-assets/angel-one-widevine/dash.mpd',
                license: 'https://cwip-shaka-proxy.appspot.com/no_auth'
            },
            ezdrmOnline: {
                media: 'https://wvm.ezdrm.com/demo/stream.mpd',
                license: 'https://widevine-dash.ezdrm.com/proxy?pX=BF9CEB'
            },
            widevineTOS: {
                media: 'https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd',
                license: 'https://proxy.uat.widevine.com/proxy?video_id=HDCP_None&provider=widevine_test'
            },
            widevineHDCP: {
                media: 'https://storage.googleapis.com/wvmedia/cenc/h264/tears/tears.mpd',
                license: 'https://proxy.uat.widevine.com/proxy?video_id=HDCP_V1&provider=widevine_test'
            },
            axTest: {
                media: 'https://media.axprod.net/TestVectors/v7-MultiDRM-SingleKey/Manifest.mpd',
                license: 'https://drm-widevine-licensing.axtest.net/AcquireLicense',
                header: 'X-AxDRM-Message',
                headerValue: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ2ZXJzaW9uIjoxLCJjb21fa2V5X2lkIjoiYjMzNjRlYjUtNTFmNi00YWUzLThjOTgtMzNjZWQ1ZTMxYzc4IiwibWVzc2FnZSI6eyJ0eXBlIjoiZW50aXRsZW1lbnRfbWVzc2FnZSIsImtleXMiOlt7ImlkIjoiOWViNDA1MGQtZTQ0Yi00ODAyLTkzMmUtMjdkNzUwODNlMjY2IiwiZW5jcnlwdGVkX2tleSI6ImxLM09qSExZVzI0Y3Iya3RSNzRmbnc9PSJ9XX19.4lWwW46k-oWcah8oN18LPj5OLS5ZU-_AQv7fe0JhNjA' 
            },
            uplynk: {
                media: 'https://content.uplynk.com/847859273a4b4a81959d8fea181672a4.mpd?pr.version=2&pr.playenabler=B621D91F-EDCC-4035-8D4B-DC71760D43E9&pr.securitylevel=150',
                license: 'https://content-ause1.uplynk.com/wv'
            },
            buyDRM: {
                media: 'https://d2jl6e4h8300i8.cloudfront.net/drm/BuyDRM/AnimationAudio_4_AAC/500-953-1406-1859/dash/stream.mpd',
                license: 'https://wv-keyos.licensekeyserver.com/',
                header: 'customdata',
                headerValue: 'PEtleU9TQXV0aGVudGljYXRpb25YTUw+PERhdGE+PEdlbmVyYXRpb25UaW1lPjIwMTYtMTEtMTkgMDk6MzQ6MDEuOTkyPC9HZW5lcmF0aW9uVGltZT48RXhwaXJhdGlvblRpbWU+MjAyNi0xMS0xOSAwOTozNDowMS45OTI8L0V4cGlyYXRpb25UaW1lPjxVbmlxdWVJZD4wZmZmMTk3YWQzMzQ0ZTMyOWU0MTA0OTIwMmQ5M2VlYzwvVW5pcXVlSWQ+PFJTQVB1YktleUlkPjdlMTE0MDBjN2RjY2QyOWQwMTc0YzY3NDM5N2Q5OWRkPC9SU0FQdWJLZXlJZD48V2lkZXZpbmVQb2xpY3kgZmxfQ2FuUGxheT0idHJ1ZSIgZmxfQ2FuUGVyc2lzdD0iZmFsc2UiIC8+PFdpZGV2aW5lQ29udGVudEtleVNwZWMgVHJhY2tUeXBlPSJIRCI+PFNlY3VyaXR5TGV2ZWw+MTwvU2VjdXJpdHlMZXZlbD48L1dpZGV2aW5lQ29udGVudEtleVNwZWM+PEZhaXJQbGF5UG9saWN5IC8+PExpY2Vuc2UgdHlwZT0ic2ltcGxlIiAvPjwvRGF0YT48U2lnbmF0dXJlPk1sNnhkcU5xc1VNalNuMDdicU8wME15bHhVZUZpeERXSHB5WjhLWElBYlAwOE9nN3dnRUFvMTlYK1c3MDJOdytRdmEzNFR0eDQydTlDUlJPU1NnREQzZTM4aXE1RHREcW9HelcwS2w2a0JLTWxHejhZZGRZOWhNWmpPTGJkNFVkRnJUbmxxU21raC9CWnNjSFljSmdaUm5DcUZIbGI1Y0p0cDU1QjN4QmtxMUREZUEydnJUNEVVcVJiM3YyV1NueUhGeVZqWDhCR3o0ZWFwZmVFeDlxSitKbWI3dUt3VjNqVXN2Y0Fab1ozSHh4QzU3WTlySzRqdk9Wc1I0QUd6UDlCc3pYSXhKd1ZSZEk3RXRoMjhZNXVEQUVZVi9hZXRxdWZiSXIrNVZOaE9yQ2JIVjhrR2praDhHRE43dC9nYWh6OWhVeUdOaXRqY2NCekJvZHRnaXdSUT09PC9TaWduYXR1cmU+PC9LZXlPU0F1dGhlbnRpY2F0aW9uWE1MPg=='
            }
        }
`

Short of it is that the Appspot, Widevine, and Shaka assets played in both platforms. The assets from Axinom, EZDRM, Uplynk, and BuyDRM played in the browser but not Electron.

**Comment by khwaaj** [comment] 2020-05-28 00:17
I did some testing with this and the services failing for you appear to be working when I use a production signed Electron version:

| Service | v8.3.0 (dev) | v8.3.0 (prod) | Comment
| :--- | :---: | :---: | :--- |
| EZDRM | No	| Yes | Long load time before working |
| Axinom | No | Yes | |
| Uplynk | No | Yes | |
| BuyDRM | No | Yes | Short clip |
| BuyDRM-2 | No | Yes | using media url (all else same): https://d2jl6e4h8300i8.cloudfront.net/netflix_meridian/4k-18.5!9/keyos-logo/g180-avc_a2.0-vbr-aac-128k/r30/dash-wv-pr/stream.mpd |

Are you sure you have signed with a production grade cert/key? If you verify the signature of the Electron build you are using with the VMP signing script, e.g. `vmp-sign.py -vv -Y /path/to/electron/`, you should **not** be seeing an extension named `Google<1.3.6.1.4.1.11129.4.1.2>` (with hex-value) if the signature is production grade.

**Comment by turbidwater** [comment] 2020-05-28 14:53
Thanks for the quick response! Yes, I am seeing the `Google<1.3.6.1.4.1.11129.4.1.2>` in the output. So then it sounds like we are not pointed at the right cert. I will dig in and see what happened to our production cert.

And thanks for the extra piece of test media!

**Comment by hindsc52** [comment] 2020-05-28 14:55
So when I first started this project I didn't have to sign electron in anyway. Why would this have stopped working now. And do you know I go about getting a signed version? I still just using this in a local dev environment.

**Comment by turbidwater** [comment] 2020-05-28 15:26
Looking at the build script we are using, it appears we are pointed at production certificates:
`python ./node_modules/electron/vmp-resign.py -C ./VMP/Signed\ by\ widevine/prod-movideon.der -P "MyPassword" -K ./VMP/production-key.pem -M "MyPlayer.app" -vv -Y ./build/mac/`

In the output, the only warnings we get are:
`
vmp-resign/WARNING: -C/--certificate is ignored for verification
vmp-resign/WARNING: -K/--key, -P/--password, -n/--no-prompt-password and -p/--prompt-password are ignored for verification
`
and
`vmp-resign/WARNING: Mach-O binary has a signature section`

We are signing the app with codesign prior to this verification. Do we need to also sign the Electron library as well before we run our production build?

**Comment by khwaaj** [comment] 2020-05-28 15:33
@turbidwater, the problem with your command line is that you are both trying to sign and verify in one step (that is why you are seeing the first two warnings). In this case only verification will be done, so you'll need to drop the `-Y` to actually sign anything.

The third warning has to do with the fact that you have code-signed the application (with Xcode or Apple tools) prior to your VMP signature. You'll need to produce the VMP signature first or you will break the code-signature (on Windows this is actually the other way around).

**Comment by khwaaj** [comment] 2020-05-28 15:41
@hindsc52, there may be several reasons why things can change depending on your particular circumstances, for example:

1. We have always only signed our Electron releases for development use, because that is what we are allowed to do at this time, which means production grade license requests will be denied (unless you have re-signed your app with a production VMP certificate). If a service were permitting developments requests initially and then change this, failures will start to appear. We have actually seen this happen in some cases. The DRM service provider is free to change the settings of their proxy at any time, which can be the cause for client-side failures.

2. Also, if you read the README, you'll find fairly common cases which break the signature, especially on Windows, so even a seemingly minor change to your build environment can impact this if you are not careful. This is a common reason for failures (aside from just misunderstandings about VMP and development/production signing). It basically means that you are required to have your own VMP certificates, issued by Google Widevine, to have a production grade application built on Electron for Content Security. We are in discussions about how to solve this particular issue, since it is a problem we have seen, particularly for small, open-source, developers that can have difficulty acquiring a certificate, but it is still an ongoing discussion.

3. Another reason for similar issues that has been fairly common is that Widevine started enforcing VMP more strictly, by default, in their Widevine proxy SDK a while back. The proxy provider (i.e the DRM provider) still has room to tune their own settings around this, but unless they do explicitly choose to be more permissive this can change the behavior of the service.

4. The CDM itself has also seen some changes over time that can influence certain things. I'm can't actually recall any particular case where I have seen this cause issues, but it is possible for some edge cases.

**Comment by turbidwater** [comment] 2020-05-28 16:20
@khwaaj Victory! Changing the signing order fixed all the assets for me! Thank you so much!

To recap, the solution that worked for me was to:
Sign Electron First:
`python ./node_modules/electron/vmp-resign.py -C ./VMP/Signed\ by\ widevine/prod-movideon.der -P "MyPassword" -K ./VMP/production-key.pem -v ./node_modules/electron/dist`

Build the app and sign with CodeSign using electron-builder:
`sudo npm run prod`

Verify the signature afterwards: 
`python ./node_modules/electron/vmp-resign.py -vv -Y -M "MyPlayer.app" -v ./build/mac/`

**Comment by khwaaj** [comment] 2020-05-28 20:49
@turbidwater, nice!

Keep in mind that this may not work on Windows though, if you are planning to build your application there as well. The signature can be broken by `electron-builder`, e.g. when it adds an icon or changes some other meta-data of the electron exe-file during packaging. Also, I think `electron-builder` doesn't actually use the binary installed in `node_modules/electron` when packaging, at least not in all cases. I believe there are some hooks provided though that you can use to re-sign at an appropriate step instead, to catch cases like that.

**Comment by NicholasEllul** [comment] 2020-06-24 19:42
@turbidwater Where did you get your production Widevine certificate from? I'm also experiencing this issue now; however, I can't seem to find clear instructions regarding the process to get a certificate to sign with

**Comment by turbidwater** [comment] 2020-06-24 21:07
@NicholasEllul The client procured it for us, but I believe the provider of the certificate was Movidone (www.movidone.com). I believe if you contact Widevine, they could also help set you up with a provider.

**Comment by khwaaj** [comment] 2020-08-26 12:14
@RohanVDeshpande, we are doing a pilot run right now, and, provided nothing unexpected happens, the service is not far off at all. Stay tuned.

**Comment by RohanVDeshpande** [comment] 2020-09-04 18:33
Thanks you for pinging me @khwaaj! I did not realized EVS was just rolled out. I'll try it out and let you know how it goes.

**Comment by khwaaj** [comment] 2020-09-21 15:15
Since [EVS](https://github.com/castlabs/electron-releases/wiki/EVS) is now available and there have been no recent updates to this issue, I'm closing it. Feel free to reopen in case there are still outstanding questions.

**Closed by khwaaj** 2020-09-21 15:15 UTC
Labels: evs, vmp

**Comment by Flydexo** [comment] 2021-05-24 10:51
I have the 500 erros but only when I install the app with the setup.exe with the win-unpacked is it ok and in test with npm start too. What is the problem ? I use the hook afterPack with this code: `
exports.default = function(ctx) {
    const { execSync } = require('child_process');
    const res = execSync('python3 -m castlabs_evs.vmp sign-pkg --persistent ./dist/win-unpacked ' + ctx.appOutDir);
    console.log(Buffer.from(res).toString());
}
` 
And I get this messages `
Signing: ./dist/win-unpacked\backbeat_streamer.exe
 - Verifying existing VMP signature
 - Signature invalid: Certificate is valid for development only
 - Verifying matching VMP signature in cache
 - Signature is valid [persistent, 3342 days of validity], use cached signature
Signing: D:\backbeat\electron\dist\win-unpacked\backbeat_streamer.exe
 - Verifying existing VMP signature
 - Signature is valid [persistent, 3342 days of validity], forego signing
`
But they are the same file so I don't understand

**Comment by khwaaj** [comment] 2021-05-24 11:13
@Flydexo, something is either different or breaks the signature in the case where you are using `setup.exe`. What kind of installer is it, I believe `electron-builder` supports several types?

Regarding the signing log it looks like you pass two directories to `sign-pkg`, first `./dist/win-unpacked` then whatever is in `ctx.appOutDir`, but the log suggests  it is actually the same directory twice. `sign-pkg` will then try to sign both these package directories, which is the reason you get the log you are seeing. It will not break anything, but it is redundant (the second time the signature is essentially just verified, since it is already valid).

**Comment by Flydexo** [comment] 2021-05-24 18:08
It is a NSIS setup: `
"build": {
    "afterPack": "./hook.js",
    "electronDownload": {
      "mirror": "https://github.com/castlabs/electron-releases/releases/download/v"
    },
    "appId": "com.backbeat.live",
    "win": {
      "target": [
        "nsis"
      ],
      "icon": "assets/images/icon.ico",
      "publish": [
        {
          "provider": "github",
          "owner": "back-beat",
          "repo": "app",
          "private": true
        }
      ]
    },
    "nsis": {
      "installerIcon": "assets/images/icon.ico",
      "uninstallerIcon": "assets/images/icon.ico",
      "uninstallDisplayName": "Backbeat",
      "oneClick": false,
      "allowToChangeInstallationDirectory": true,
      "shortcutName": "Backbeat",
      "createStartMenuShortcut": true,
      "menuCategory": true
    }
  }
`.

**Comment by Flydexo** [comment] 2021-05-24 18:13
Now I have development only and It only works on de npm start version except I resign the dist/win-unpacked

**Comment by khwaaj** [comment] 2021-05-25 06:41
I'm not sure I follow exactly what you have tried here, but we have seen some issues around portable NSIS packages. These are actually self-extracting archives and uncompresses to a temporary location when run. Depending on the machine configuration this location may be incompatible with the Chromium sandbox and/or VMP verification, and thus makes it impossible to get Widevine licenses from servers that require VMP.

AFAICT what you are using is a real installer though, and not the portable NSIS format, right? In that case I would suggest you use the EVS tool with the `verify-pkg` subcommand on the machine that you have installed the package on to make sure that the VMP signature is indeed intact. If it is there is likely some environmental issue. For example you cannot run ECS from any kind of virtualized drive/filesystem, like a SUBSTed drive letter, because it conflicts with the sandboxing and prevents correct initialization wf Widevine/VMP. OTOH, if the signature is not intact after installing you have a packaging issue.

**Comment by Flydexo** [comment] 2021-05-25 15:48
I replaced my nsis config to a msi config but nothing changed, I the setup version doesn't work and I need to sign it manually to make it works

**Comment by khwaaj** [comment] 2021-05-25 18:00
I just realized you are using the `afterPack` hook, are you by any chance also code-signing the executable? On Windows the code-signing breaks the VMP signature so the [VMP signing needs to take place after](https://github.com/castlabs/electron-releases/wiki/EVS#signing-an-ecs-application-package). You can achieve this by doing the VMP signing in `afterSign` instead.

**Comment by Flydexo** [comment] 2021-05-25 19:18
Thank you very much, it works. But can you explain what caused my problem and how the signature process works on windows etc..  Because I think I am not the only one in that case ? And do you think it will work on nsis ? Because with msi I can't edit the file destination etc...

**Comment by khwaaj** [comment] 2021-05-25 19:54
This behavior is actually documented in the link I provided above and it relates to how code-signing and VMP-signing works and interacts on the different platforms.

On Windows, like in this case, the code-signing makes changes to the executable itself to store the signature that is generated. The VMP implementation on Windows does not allow any changes to a signed executable, so if the VMP-signature is generated before code-signing it will be broken by the change that code-signing makes. On macOS it is the opposite because of how app-bundles, code-signing and VMP-signing interacts there.
