### ISSUE TITLE
Library not loaded

### ISSUE THREAD

**Issue by jtvberg** [castlabs/electron-releases#145] opened 2023-02-11 02:51 UTC
On macOs 12.6.3
After a clean install of 23.0.0 when I start the app I get this:

```
dyld[42893]: Library not loaded: '@rpath/Electron Framework.framework/Electron Framework'
  Referenced from: '.../node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'
  Reason: tried: '.../node_modules/electron/dist/Electron.app/Contents/MacOS/../Frameworks/ElectronFramework.framework/Electron Framework' (no such file)
```
Navigating the file tree I can see the 'Electron Framework' at the location specified.

I went back to 22.x.x, 21.x.x and same problem.
If I go back to 18.3.15 it works!
Vanilla 23.0.0 works too.

I have tried cleaning my npm cache and searching within the posted issues and beyond.
Any ideas?

**Comment by khwaaj** [comment] 2023-02-11 10:22
I think this is this is a duplicate of #144. There is some kind of problem wit `npm` not properly preserving symlinks when extracting the ECS zip file, and we have not been able to find a solution so far. There are a few workarounds is suggested in #144 though.

**Comment by jtvberg** [comment] 2023-02-11 16:27
Makes sense. I didn't think of it being a symlink problem so I didn't search for that. I'll try a work-around as outlined.
Sorry for the dupe and thanks for the quick response!

**Comment by khwaaj** [comment] 2023-03-03 10:38
I'll go ahead and close this as a dupe, please reopen if this turned out to be some other problem after all.

**Closed by khwaaj** 2023-03-03 10:38 UTC
Labels: duplicate
